### ISSUE TITLE
Cannot create blog post with same Title

### ISSUE THREAD

**Issue by arryanggaputra** [antoniputra/ngeblog#16]
In every blogging platform, we able to create multiple post with duplication blog title, unfortunately this feature is not implemented now.

```sql
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'lorem-ipsum' for key 'ngeblog_blogs_slug_unique' (SQL: insert into `ngeblog_blogs` (`title`, `category_id`, `status`, `editor_type`, `content`, `user_id`, `slug`, `updated_at`, `created_at`) values (lorem ipsum, 1, publish, quill, <p>asdfasd asdf asdf asdf</p>, 0, generate-tahanan-lebih-dari-81-hari, 2017-12-10 01:50:59, 2017-12-10 01:50:59))
```

Maybe we can add some random unique number when generate the slug value, like this 👍 

```php
// src/Repositories/BlogRepository.php
$model->slug = str_random(5).'-'.str_slug($data['title']);
//or
$model->slug = time().'-'.str_slug($data['title']);
```

**Comment by antoniputra** [comment]
looks Make a sense..

but instead of your solution, what about if we provide `slug input`, so User can input slug itself. I thought this approach more better..

**Comment by arryanggaputra** [comment]
@antoniputra yes good. Like wordpress feature, we can create custom slug. I'm waiting for this.
