### ISSUE TITLE
Tombol delete tidak bekerja

### ISSUE THREAD

**Issue by nafiesl** [antoniputra/ngeblog#8]
Terima kasih sudah bikin paket ini, mas Antoni. Saya sudah mencoba paket ini dan sudah jalan baik. Tapi ada sedikit problem saat kita mau hapus item blog dan item kategori.

Ketika kita klik tombol Hapus, munculnya hanya halaman blank. Setelah dicek, ternyata actionnya masuknya ke controller `BlogsController@show`, **bukan** ke `BlogsController@destroy`.

Sehingga **recordnya tidak terhapus** dari database.

Terima kasih.

![shutter_20171206-008](https://user-images.githubusercontent.com/8721551/33645704-12998420-da87-11e7-8f0c-cfb1a6b45609.jpg)

**Comment by antoniputra** [comment]
Thankyou sudah report mas..

tampaknya saya sedikit teledor.. will fix this asap :-D

**Comment by antoniputra** [comment]
#9
